-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 2017  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Intel Program License
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel MegaCore Function License Agreement, or other
-- applicable license agreement, including, without limitation,
-- that your use is for the sole purpose of programming logic
-- devices manufactured by Intel and sold by Intel or its
-- authorized distributors.  Please refer to the applicable
-- agreement for further details.


-- Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
-- Created on Tue Jul 25 15:00:27 2017

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

--  Entity Declaration

ENTITY block_cnt IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		MCK : IN STD_LOGIC;
		DIN : IN STD_LOGIC_VECTOR(3 downto 0);
		EN_L : IN STD_LOGIC;
		CLR_L : IN STD_LOGIC;
		LD_L : IN STD_LOGIC;
		CARRY : OUT STD_LOGIC;
		DOUT : OUT STD_LOGIC_VECTOR(3 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END block_cnt;

--  Architecture Body

ARCHITECTURE block_cnt_architecture OF block_cnt IS
  signal DOUTx: STD_LOGIC_VECTOR(3 downto 0) := "0000";

BEGIN
	process(MCK)
	begin
		if (EN_L = '0') then
			if (MCK'event and MCK = '1') then
				if (CLR_L = '0') then
					DOUTx <= "0000";
				else
					if (LD_L = '0') then
						DOUTx <= DIN;
					else
						DOUTx <= DOUTx + "1";
					end if;
				end if;
			end if;
		end if;
	end process;
	CARRY <= '1' when DOUTx="1111" else '0';
	DOUT <= DOUTx;
END block_cnt_architecture;
